//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerScore_WPF_edition.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoccerScore_WPF_edition.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string captain {
            get {
                return ResourceManager.GetString("captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string draws {
            get {
                return ResourceManager.GetString("draws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wan&apos;t to exit?.
        /// </summary>
        public static string exit_question {
            get {
                return ResourceManager.GetString("exit_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code:.
        /// </summary>
        public static string fifacode {
            get {
                return ResourceManager.GetString("fifacode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string games_played {
            get {
                return ResourceManager.GetString("games_played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal differential:.
        /// </summary>
        public static string goal_differential {
            get {
                return ResourceManager.GetString("goal_differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string goals {
            get {
                return ResourceManager.GetString("goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals against:.
        /// </summary>
        public static string goals_against {
            get {
                return ResourceManager.GetString("goals_against", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for:.
        /// </summary>
        public static string goals_for {
            get {
                return ResourceManager.GetString("goals_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string large {
            get {
                return ResourceManager.GetString("large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string losses {
            get {
                return ResourceManager.GetString("losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men&apos;s world cup.
        /// </summary>
        public static string mens_wc {
            get {
                return ResourceManager.GetString("mens_wc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National team.
        /// </summary>
        public static string national_team {
            get {
                return ResourceManager.GetString("national_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponents:.
        /// </summary>
        public static string opponents {
            get {
                return ResourceManager.GetString("opponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string small {
            get {
                return ResourceManager.GetString("small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points:.
        /// </summary>
        public static string total_points {
            get {
                return ResourceManager.GetString("total_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window settings.
        /// </summary>
        public static string window_settings {
            get {
                return ResourceManager.GetString("window_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string wins {
            get {
                return ResourceManager.GetString("wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s world cup.
        /// </summary>
        public static string womens_wc {
            get {
                return ResourceManager.GetString("womens_wc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards.
        /// </summary>
        public static string yellow_cards {
            get {
                return ResourceManager.GetString("yellow_cards", resourceCulture);
            }
        }
    }
}
